version: "3.9"

services:
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    volumes:
      - ./public:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: secret
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    networks:
      - app-network

  node:
    image: node:20
    container_name: node
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "5173:5173"
    networks:
      - app-network

volumes:
  mariadb_data:

networks:
  app-network:
    driver: bridge
